[package]
name = "dotapi"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.31.1"
egui = "0.31.1"
ehttp = "0.5.0"
tokio = { version = "1.44.2", features = ["full"] }

[workspace]
resolver = "2"
members = ["cli"]
