[package]
name = "rustle-ui-components"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { version = "0.6.0" }
dioxus-desktop = { version = "0.6.3"}
dioxus-free-icons = { version = "0.9", features = ["lucide"] }
