name: Build and Release

on:
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Create a GitHub release'
        required: false
        default: false
        type: boolean
      tag_name:
        description: 'Tag name for the release (e.g., v1.0.0)'
        required: false
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  build-desktop:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Install system dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt install libwebkit2gtk-4.1-dev \
        build-essential \
        curl \
        wget \
        file \
        libxdo-dev \
        libssl-dev \
        libayatana-appindicator3-dev \
        librsvg2-dev
    - name: Install dioxus-cli
      run: cargo install dioxus-cli
    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
    - name: Build desktop app
      run: |
        dx build -p app --platform desktop --release
    - name: Upload desktop build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: desktop-build-${{ matrix.os }}
        path: app/dist/

  release:
    needs: [build-desktop]
    runs-on: ubuntu-latest
    if: inputs.create_release
    steps:
    - uses: actions/checkout@v4
    - name: Download all artifacts
      uses: actions/download-artifact@v4
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ inputs.tag_name || github.sha }}
        files: |
          desktop-build-*/**/*
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
